### ISSUE TITLE
Virtual Clusters - Configure how the APIserver will be exposed

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/ux#223]
**Context**
The k3k cluster creation UI should include fields to configure the [expose](https://github.com/rancher/k3k/blob/main/docs/crds/crd-docs.md#exposeconfig) property, which determines how the api server will be exposed

```
ingress:
    annotations: object (keys:string, values:string)
    ingressClassName: string
loadBalancer:
nodePort:
    serverPort: integer
    servicePort: integer
    etcdPort: integer
```

**Related UI issue**
https://github.com/rancher/virtual-clusters-ui/issues/14

**Solution**
[Figma prototype](https://www.figma.com/design/aa7QWiBymyONkE9l4hlwn1/Virtual-Clusters?node-id=364-537&t=EjhspNtHtemUjT7H-1)
